"""Write the slice's cell lines into configs/slice.yaml from what was actually screened.

Lines = every cell line with pass_filter == 'full' cells on the config's plates (one aggregate
query on the remote metadata). DepMap ID and tissue come from Tahoe's cell_line_metadata. A line
without a DepMap ID stops the script unless it is named with --allow-missing-depmap LINE=REASON;
it is then written as depmap_id: null with that reason, which the phase 1 contract accepts.

Only the block between the BEGIN/END markers is rewritten; everything else in the file is kept.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from phase1.config import load_slice_config
from phase1.stream import connect, sql_list

CONFIG_PATH = ROOT / "configs" / "slice.yaml"
TAHOE_CELL_LINES = ROOT / "data" / "cache" / "cell_line_metadata.parquet"
METADATA_URL = "https://huggingface.co/datasets/tahoebio/Tahoe-100M/resolve/main/metadata/obs_metadata.parquet"
BEGIN = "# BEGIN cell lines - generated by scripts/make_slice_lines.py, do not edit by hand"
END = "# END cell lines"


def screened_lines(plates: list[str]) -> pd.DataFrame:
    """(cell_line, n_cells) for lines with pass_filter == 'full' cells on these plates, most cells first."""
    con = connect("2GB", ROOT / "data" / "cache" / "duckdb_tmp", remote=True)
    return con.execute(
        f"""
        SELECT cell_line, count(*) AS n_cells
        FROM read_parquet('{METADATA_URL}')
        WHERE list_contains({sql_list(plates)}, plate) AND pass_filter = 'full'
        GROUP BY cell_line ORDER BY n_cells DESC, cell_line
        """
    ).df()


def slice_lines(screened: pd.DataFrame, tahoe: pd.DataFrame, allow_missing: dict[str, str]) -> pd.DataFrame:
    """Screened lines joined to Tahoe metadata, in screened order; raises on unknown lines or undeclared missing DepMap IDs."""
    info = (
        tahoe[["Cell_ID_Cellosaur", "cell_name", "Cell_ID_DepMap", "Organ"]]
        .drop_duplicates("Cell_ID_Cellosaur")
        .rename(columns={"Cell_ID_Cellosaur": "cell_line", "Cell_ID_DepMap": "depmap_id", "Organ": "tissue"})
    )
    lines = screened[["cell_line", "n_cells"]].merge(info, on="cell_line", how="left", validate="one_to_one")
    unknown = sorted(lines.loc[lines["cell_name"].isna(), "cell_line"])
    if unknown:
        raise ValueError(f"screened line(s) missing from Tahoe cell_line_metadata: {unknown}")
    no_depmap = set(lines.loc[lines["depmap_id"].isna(), "cell_line"])
    undeclared = sorted(no_depmap - set(allow_missing))
    if undeclared:
        raise ValueError(f"line(s) without a DepMap ID: {undeclared}; pass --allow-missing-depmap LINE=REASON")
    lines["depmap_absent"] = lines["cell_line"].map(lambda line: allow_missing.get(line) if line in no_depmap else None)
    return lines.reset_index(drop=True)


def render_block(lines: pd.DataFrame) -> str:
    """YAML for selected_cell_lines and cell_line_info, one line per cell line, name and cells as comments."""
    out = ["selected_cell_lines:"]
    out += [f"  - {line}" for line in lines["cell_line"]]
    out += ["", "# DepMap ID and tissue from tahoebio/Tahoe-100M metadata/cell_line_metadata.parquet.", "cell_line_info:"]
    for row in lines.itertuples():
        if pd.notna(row.depmap_absent):
            fields = f"depmap_id: null, depmap_absent: \"{row.depmap_absent}\", tissue: {row.tissue}"
        else:
            fields = f"depmap_id: {row.depmap_id}, tissue: {row.tissue}"
        out.append(f"  {row.cell_line}: {{{fields}}}  # {row.cell_name}, {row.n_cells:,} cells")
    return "\n".join(out) + "\n"


def replace_block(text: str, block: str) -> str:
    """Replace everything between the BEGIN and END marker lines with block."""
    if BEGIN not in text or END not in text:
        raise ValueError(f"config is missing the generated-block marker lines ({BEGIN!r} / {END!r})")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{BEGIN}\n{block}{END}{tail}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--config", type=Path, default=CONFIG_PATH)
    parser.add_argument("--allow-missing-depmap", action="append", default=[], metavar="LINE=REASON",
                        help="Declare a line that has no DepMap ID, with the reason written into the config.")
    args = parser.parse_args()

    allow_missing = dict(item.split("=", 1) for item in args.allow_missing_depmap)
    config = load_slice_config(args.config)
    screened = screened_lines(list(config["plates"]))
    lines = slice_lines(screened, pd.read_parquet(TAHOE_CELL_LINES), allow_missing)
    args.config.write_text(replace_block(args.config.read_text(encoding="utf-8"), render_block(lines)), encoding="utf-8")
    print(f"{len(lines)} lines written to {args.config}; per tissue:")
    print(lines["tissue"].value_counts().to_string())
    for row in lines[lines["depmap_absent"].notna()].itertuples():
        print(f"no DepMap ID (declared): {row.cell_line} {row.cell_name}: {row.depmap_absent}")


if __name__ == "__main__":
    main()
