"""reports/results.md, generated from data/eval/results/*/results.json (evaluation.md §10). Never hand-written."""
from __future__ import annotations

import json
from pathlib import Path

from phase4.splits import SPLITS

PRIMARY = ["de_pearson", "topk_overlap_50", "topk_overlap_100", "disc_rank_global", "disc_rank_within_line"]
LOWER_IS_BETTER = {"disc_rank_global", "disc_rank_within_line", "de_mse"}


def _cell(row: dict | None) -> str:
    if row is None or row.get("estimate") is None or row["estimate"] != row["estimate"]:
        return "—"
    return f"{row['estimate']:.3f} [{row['ci_low']:.3f}, {row['ci_high']:.3f}]"


def render_results(results_dir: Path) -> str:
    results = [json.loads(p.read_text()) for p in sorted(Path(results_dir).glob("*/results.json"))]
    metrics = [m for m in PRIMARY if any(m in r["summaries"] for r in results)] or sorted({m for r in results for m in r["summaries"]})
    lines = [
        "# Results",
        "",
        "Generated by `make results` from `data/eval/results/*/results.json`; do not edit.",
        "Cells: mean over 5 split repeats of the per-repeat median, [95% interval] from a within-repeat bootstrap",
        "(evaluation.md §7). Discrimination ranks: lower is better (0 = best, 0.5 = chance).",
        "",
    ]
    for metric in metrics:
        lines += [f"## {metric}" + (" (lower is better)" if metric in LOWER_IS_BETTER else ""), ""]
        lines += ["| model | " + " | ".join(SPLITS) + " |", "|---|" + "---|" * len(SPLITS)]
        for r in results:
            by_split = {row["split"]: row for row in r["summaries"].get(metric, [])}
            lines.append(f"| {r['model']} | " + " | ".join(_cell(by_split.get(s)) for s in SPLITS) + " |")
        lines.append("")
    lines += ["## Runs", "", "| model | runtime (s) | peak RSS (MB) |", "|---|---|---|"]
    lines += [f"| {r['model']} | {r['runtime_s']} | {r['peak_rss_mb']} |" for r in results]
    return "\n".join(lines) + "\n"
